#!/usr/bin/env bash
# Bash script to identify the multiples of 3 annd 5 in a compilation of numbers from 1 to 100

i=1

while (( i <= 100 ));
do
	if (( i%15 == 0 ));
	then
	    echo "FizzBuzz"
	elif (( i%5 == 0 ));
	then
	    echo "Buzz"
	elif (( i%3 == 0 ));
	then
	    echo "Fizz"
	else 
	    echo -e "$i"
	fi
	i=$((i+1))
done
