#!/usr/bin/env bash
# Bash script that loops from 1 to 10, it will display "bad luck" on the 4th iteration and "good luck" for the 8th iteration

i=0

while (( i < 10 ));
do
    if (( i == 3 ))
    then
	echo "bad luck"
    elif (( i == 7 ))
    then
	echo "good luck"
    else
	echo "Best School"
    fi
	i=$((i+1))
done
