#!/usr/bin/env bash
# bash script that displays a list of number from 1 to 20 and the bad luck number for several countries

i=1

while (( i < 21 ));
do
	case $i in
	     4)
		echo -e "$i\nbad luck from China"
		;;
	     9)
		echo -e "$i\nbad luck from Japan"
		;;
	     17)
		echo -e "$i\nbad luck from Italy"
		;;
	     *)
		echo $i
	esac
	i=$((i+1))
done
