#!/usr/bin/env bash
# clock that display the 12 hours and the 59 minutes

x=0

while (( x <= 12 ));
do
    echo -e "Hour: $x"
    x=$((x+1))
    i=1
    while (( i <= 59));
    do
	echo -e "$i"
	i=$((i+1))
    done
done
